<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.kbalazs</groupId>
    <artifactId>smart_scrum_poker_backend_native</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>smart_scrum_poker_backend_native</name>
    <description>smart_scrum_poker_backend_native</description>
    <packaging>pom</packaging>

    <modules>
        <module>app-module</module>
        <module>db-module</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <aspectj.version>1.9.22</aspectj.version>
        <postgresql.version>42.7.3</postgresql.version>
        <jooq.version>3.19.21</jooq.version>
        <flyway.version>10.10.0</flyway.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.3.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
