/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PokerRecord extends UpdatableRecordImpl<PokerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.poker.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.poker.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.poker.public_id</code>.
     */
    public void setPublicId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.poker.public_id</code>.
     */
    public UUID getPublicId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.poker.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.poker.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.poker.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.poker.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.poker.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.poker.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PokerRecord
     */
    public PokerRecord() {
        super(Poker.POKER);
    }

    /**
     * Create a detached, initialised PokerRecord
     */
    public PokerRecord(Long id, UUID publicId, String name, LocalDateTime createdAt, UUID createdBy) {
        super(Poker.POKER);

        setId(id);
        setPublicId(publicId);
        setName(name);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
