/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.StoryPointConfig;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoryPointConfigRecord extends UpdatableRecordImpl<StoryPointConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.story_point_config.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.story_point_config.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.story_point_config.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.story_point_config.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.story_point_config.sizes_config</code>.
     */
    public void setSizesConfig(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.story_point_config.sizes_config</code>.
     */
    public JSONB getSizesConfig() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.story_point_config.dimensions_config</code>.
     */
    public void setDimensionsConfig(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.story_point_config.dimensions_config</code>.
     */
    public JSONB getDimensionsConfig() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.story_point_config.points_mapping</code>.
     */
    public void setPointsMapping(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.story_point_config.points_mapping</code>.
     */
    public JSONB getPointsMapping() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.story_point_config.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.story_point_config.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.story_point_config.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.story_point_config.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoryPointConfigRecord
     */
    public StoryPointConfigRecord() {
        super(StoryPointConfig.STORY_POINT_CONFIG);
    }

    /**
     * Create a detached, initialised StoryPointConfigRecord
     */
    public StoryPointConfigRecord(Long id, String name, JSONB sizesConfig, JSONB dimensionsConfig, JSONB pointsMapping, LocalDateTime createdAt, UUID createdBy) {
        super(StoryPointConfig.STORY_POINT_CONFIG);

        setId(id);
        setName(name);
        setSizesConfig(sizesConfig);
        setDimensionsConfig(dimensionsConfig);
        setPointsMapping(pointsMapping);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
