/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VoteRecord extends UpdatableRecordImpl<VoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vote.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vote.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vote.ticket_id</code>.
     */
    public void setTicketId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vote.ticket_id</code>.
     */
    public Long getTicketId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.vote.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vote.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.vote.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vote.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.vote.story_point_config_id</code>.
     */
    public void setStoryPointConfigId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vote.story_point_config_id</code>.
     */
    public Long getStoryPointConfigId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.vote.vote_values</code>.
     */
    public void setVoteValues(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vote.vote_values</code>.
     */
    public JSONB getVoteValues() {
        return (JSONB) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoteRecord
     */
    public VoteRecord() {
        super(Vote.VOTE);
    }

    /**
     * Create a detached, initialised VoteRecord
     */
    public VoteRecord(Long id, Long ticketId, LocalDateTime createdAt, UUID createdBy, Long storyPointConfigId, JSONB voteValues) {
        super(Vote.VOTE);

        setId(id);
        setTicketId(ticketId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setStoryPointConfigId(storyPointConfigId);
        setVoteValues(voteValues);
        resetChangedOnNotNull();
    }
}
