/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VoteRecord extends UpdatableRecordImpl<VoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vote.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vote.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vote.ticket_id</code>.
     */
    public void setTicketId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vote.ticket_id</code>.
     */
    public Long getTicketId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.vote.uncertainty</code>.
     */
    public void setUncertainty(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vote.uncertainty</code>.
     */
    public Short getUncertainty() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.vote.complexity</code>.
     */
    public void setComplexity(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vote.complexity</code>.
     */
    public Short getComplexity() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.vote.effort</code>.
     */
    public void setEffort(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vote.effort</code>.
     */
    public Short getEffort() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.vote.risk</code>.
     */
    public void setRisk(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vote.risk</code>.
     */
    public Short getRisk() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.vote.calculated_point</code>.
     */
    public void setCalculatedPoint(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vote.calculated_point</code>.
     */
    public Short getCalculatedPoint() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.vote.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.vote.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.vote.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.vote.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VoteRecord
     */
    public VoteRecord() {
        super(Vote.VOTE);
    }

    /**
     * Create a detached, initialised VoteRecord
     */
    public VoteRecord(Long id, Long ticketId, Short uncertainty, Short complexity, Short effort, Short risk, Short calculatedPoint, LocalDateTime createdAt, UUID createdBy) {
        super(Vote.VOTE);

        setId(id);
        setTicketId(ticketId);
        setUncertainty(uncertainty);
        setComplexity(complexity);
        setEffort(effort);
        setRisk(risk);
        setCalculatedPoint(calculatedPoint);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
