/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUserSessions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IdsUserSessionsRecord extends UpdatableRecordImpl<IdsUserSessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ids_user_sessions.ids_user_id</code>.
     */
    public void setIdsUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ids_user_sessions.ids_user_id</code>.
     */
    public UUID getIdsUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.ids_user_sessions.session_id</code>.
     */
    public void setSessionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ids_user_sessions.session_id</code>.
     */
    public UUID getSessionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.ids_user_sessions.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ids_user_sessions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IdsUserSessionsRecord
     */
    public IdsUserSessionsRecord() {
        super(IdsUserSessions.IDS_USER_SESSIONS);
    }

    /**
     * Create a detached, initialised IdsUserSessionsRecord
     */
    public IdsUserSessionsRecord(UUID idsUserId, UUID sessionId, LocalDateTime createdAt) {
        super(IdsUserSessions.IDS_USER_SESSIONS);

        setIdsUserId(idsUserId);
        setSessionId(sessionId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
