/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IdsUserRecord extends TableRecordImpl<IdsUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ids_user.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ids_user.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.ids_user.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ids_user.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IdsUserRecord
     */
    public IdsUserRecord() {
        super(IdsUser.IDS_USER);
    }

    /**
     * Create a detached, initialised IdsUserRecord
     */
    public IdsUserRecord(UUID id, LocalDateTime createdAt) {
        super(IdsUser.IDS_USER);

        setId(id);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
