/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InGamePlayers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InGamePlayersRecord extends UpdatableRecordImpl<InGamePlayersRecord> implements Record3<UUID, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1839425777;

    /**
     * Setter for <code>public.in_game_players.insecure_user_id_secure</code>.
     */
    public void setInsecureUserIdSecure(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.in_game_players.insecure_user_id_secure</code>.
     */
    public UUID getInsecureUserIdSecure() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.in_game_players.poker_id_secure</code>.
     */
    public void setPokerIdSecure(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.in_game_players.poker_id_secure</code>.
     */
    public UUID getPokerIdSecure() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.in_game_players.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.in_game_players.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return InGamePlayers.IN_GAME_PLAYERS.INSECURE_USER_ID_SECURE;
    }

    @Override
    public Field<UUID> field2() {
        return InGamePlayers.IN_GAME_PLAYERS.POKER_ID_SECURE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return InGamePlayers.IN_GAME_PLAYERS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getInsecureUserIdSecure();
    }

    @Override
    public UUID component2() {
        return getPokerIdSecure();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getInsecureUserIdSecure();
    }

    @Override
    public UUID value2() {
        return getPokerIdSecure();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public InGamePlayersRecord value1(UUID value) {
        setInsecureUserIdSecure(value);
        return this;
    }

    @Override
    public InGamePlayersRecord value2(UUID value) {
        setPokerIdSecure(value);
        return this;
    }

    @Override
    public InGamePlayersRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public InGamePlayersRecord values(UUID value1, UUID value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InGamePlayersRecord
     */
    public InGamePlayersRecord() {
        super(InGamePlayers.IN_GAME_PLAYERS);
    }

    /**
     * Create a detached, initialised InGamePlayersRecord
     */
    public InGamePlayersRecord(UUID insecureUserIdSecure, UUID pokerIdSecure, LocalDateTime createdAt) {
        super(InGamePlayers.IN_GAME_PLAYERS);

        set(0, insecureUserIdSecure);
        set(1, pokerIdSecure);
        set(2, createdAt);
    }
}
