/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InPokerIdsUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InPokerIdsUsersRecord extends UpdatableRecordImpl<InPokerIdsUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.in_poker_ids_users.ids_user_id</code>.
     */
    public void setIdsUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.in_poker_ids_users.ids_user_id</code>.
     */
    public UUID getIdsUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.in_poker_ids_users.poker_id</code>.
     */
    public void setPokerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.in_poker_ids_users.poker_id</code>.
     */
    public Long getPokerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.in_poker_ids_users.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.in_poker_ids_users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InPokerIdsUsersRecord
     */
    public InPokerIdsUsersRecord() {
        super(InPokerIdsUsers.IN_POKER_IDS_USERS);
    }

    /**
     * Create a detached, initialised InPokerIdsUsersRecord
     */
    public InPokerIdsUsersRecord(UUID idsUserId, Long pokerId, LocalDateTime createdAt) {
        super(InPokerIdsUsers.IN_POKER_IDS_USERS);

        setIdsUserId(idsUserId);
        setPokerId(pokerId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
