/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InsecureUserSessions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InsecureUserSessionsRecord extends UpdatableRecordImpl<InsecureUserSessionsRecord> implements Record3<UUID, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1450032519;

    /**
     * Setter for <code>public.insecure_user_sessions.insecure_user_id_secure</code>.
     */
    public void setInsecureUserIdSecure(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.insecure_user_sessions.insecure_user_id_secure</code>.
     */
    public UUID getInsecureUserIdSecure() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.insecure_user_sessions.session_id</code>.
     */
    public void setSessionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.insecure_user_sessions.session_id</code>.
     */
    public UUID getSessionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.insecure_user_sessions.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.insecure_user_sessions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return InsecureUserSessions.INSECURE_USER_SESSIONS.INSECURE_USER_ID_SECURE;
    }

    @Override
    public Field<UUID> field2() {
        return InsecureUserSessions.INSECURE_USER_SESSIONS.SESSION_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return InsecureUserSessions.INSECURE_USER_SESSIONS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getInsecureUserIdSecure();
    }

    @Override
    public UUID component2() {
        return getSessionId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getInsecureUserIdSecure();
    }

    @Override
    public UUID value2() {
        return getSessionId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public InsecureUserSessionsRecord value1(UUID value) {
        setInsecureUserIdSecure(value);
        return this;
    }

    @Override
    public InsecureUserSessionsRecord value2(UUID value) {
        setSessionId(value);
        return this;
    }

    @Override
    public InsecureUserSessionsRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public InsecureUserSessionsRecord values(UUID value1, UUID value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InsecureUserSessionsRecord
     */
    public InsecureUserSessionsRecord() {
        super(InsecureUserSessions.INSECURE_USER_SESSIONS);
    }

    /**
     * Create a detached, initialised InsecureUserSessionsRecord
     */
    public InsecureUserSessionsRecord(UUID insecureUserIdSecure, UUID sessionId, LocalDateTime createdAt) {
        super(InsecureUserSessions.INSECURE_USER_SESSIONS);

        set(0, insecureUserIdSecure);
        set(1, sessionId);
        set(2, createdAt);
    }
}
