/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InsecureUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InsecureUserRecord extends UpdatableRecordImpl<InsecureUserRecord> implements Record4<Long, UUID, String, LocalDateTime> {

    private static final long serialVersionUID = -1477969585;

    /**
     * Setter for <code>public.insecure_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.insecure_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.insecure_user.id_secure</code>.
     */
    public void setIdSecure(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.insecure_user.id_secure</code>.
     */
    public UUID getIdSecure() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.insecure_user.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.insecure_user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.insecure_user.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.insecure_user.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, UUID, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, UUID, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return InsecureUser.INSECURE_USER.ID;
    }

    @Override
    public Field<UUID> field2() {
        return InsecureUser.INSECURE_USER.ID_SECURE;
    }

    @Override
    public Field<String> field3() {
        return InsecureUser.INSECURE_USER.USER_NAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return InsecureUser.INSECURE_USER.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getIdSecure();
    }

    @Override
    public String component3() {
        return getUserName();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getIdSecure();
    }

    @Override
    public String value3() {
        return getUserName();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public InsecureUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InsecureUserRecord value2(UUID value) {
        setIdSecure(value);
        return this;
    }

    @Override
    public InsecureUserRecord value3(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public InsecureUserRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public InsecureUserRecord values(Long value1, UUID value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InsecureUserRecord
     */
    public InsecureUserRecord() {
        super(InsecureUser.INSECURE_USER);
    }

    /**
     * Create a detached, initialised InsecureUserRecord
     */
    public InsecureUserRecord(Long id, UUID idSecure, String userName, LocalDateTime createdAt) {
        super(InsecureUser.INSECURE_USER);

        set(0, id);
        set(1, idSecure);
        set(2, userName);
        set(3, createdAt);
    }
}
