/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables.records;


import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Ticket;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TicketRecord extends UpdatableRecordImpl<TicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ticket.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ticket.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ticket.public_id</code>.
     */
    public void setPublicId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ticket.public_id</code>.
     */
    public UUID getPublicId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.ticket.poker_id</code>.
     */
    public void setPokerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ticket.poker_id</code>.
     */
    public Long getPokerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.ticket.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ticket.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.ticket.active</code>.
     */
    public void setActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ticket.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketRecord
     */
    public TicketRecord() {
        super(Ticket.TICKET);
    }

    /**
     * Create a detached, initialised TicketRecord
     */
    public TicketRecord(Long id, UUID publicId, Long pokerId, String name, Boolean active) {
        super(Ticket.TICKET);

        setId(id);
        setPublicId(publicId);
        setPokerId(pokerId);
        setName(name);
        setActive(active);
        resetChangedOnNotNull();
    }
}
