/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.FlywaySchemaHistory;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InGamePlayers;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InsecureUser;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InsecureUserSessions;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Ticket;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1264428880;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.in_game_players</code>.
     */
    public final InGamePlayers IN_GAME_PLAYERS = InGamePlayers.IN_GAME_PLAYERS;

    /**
     * The table <code>public.insecure_user</code>.
     */
    public final InsecureUser INSECURE_USER = InsecureUser.INSECURE_USER;

    /**
     * The table <code>public.insecure_user_sessions</code>.
     */
    public final InsecureUserSessions INSECURE_USER_SESSIONS = InsecureUserSessions.INSECURE_USER_SESSIONS;

    /**
     * The table <code>public.poker</code>.
     */
    public final Poker POKER = Poker.POKER;

    /**
     * The table <code>public.ticket</code>.
     */
    public final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>public.vote</code>.
     */
    public final Vote VOTE = Vote.VOTE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            InGamePlayers.IN_GAME_PLAYERS,
            InsecureUser.INSECURE_USER,
            InsecureUserSessions.INSECURE_USER_SESSIONS,
            Poker.POKER,
            Ticket.TICKET,
            Vote.VOTE);
    }
}
