/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.Keys;
import org.kbalazs.smart_scrum_poker_backend_native.db.Public;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser.IdsUserPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.IdsUserSessionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IdsUserSessions extends TableImpl<IdsUserSessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ids_user_sessions</code>
     */
    public static final IdsUserSessions IDS_USER_SESSIONS = new IdsUserSessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IdsUserSessionsRecord> getRecordType() {
        return IdsUserSessionsRecord.class;
    }

    /**
     * The column <code>public.ids_user_sessions.ids_user_id</code>.
     */
    public final TableField<IdsUserSessionsRecord, UUID> IDS_USER_ID = createField(DSL.name("ids_user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.ids_user_sessions.session_id</code>.
     */
    public final TableField<IdsUserSessionsRecord, UUID> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.ids_user_sessions.created_at</code>.
     */
    public final TableField<IdsUserSessionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private IdsUserSessions(Name alias, Table<IdsUserSessionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IdsUserSessions(Name alias, Table<IdsUserSessionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ids_user_sessions</code> table reference
     */
    public IdsUserSessions(String alias) {
        this(DSL.name(alias), IDS_USER_SESSIONS);
    }

    /**
     * Create an aliased <code>public.ids_user_sessions</code> table reference
     */
    public IdsUserSessions(Name alias) {
        this(alias, IDS_USER_SESSIONS);
    }

    /**
     * Create a <code>public.ids_user_sessions</code> table reference
     */
    public IdsUserSessions() {
        this(DSL.name("ids_user_sessions"), null);
    }

    public <O extends Record> IdsUserSessions(Table<O> path, ForeignKey<O, IdsUserSessionsRecord> childPath, InverseForeignKey<O, IdsUserSessionsRecord> parentPath) {
        super(path, childPath, parentPath, IDS_USER_SESSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IdsUserSessionsPath extends IdsUserSessions implements Path<IdsUserSessionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IdsUserSessionsPath(Table<O> path, ForeignKey<O, IdsUserSessionsRecord> childPath, InverseForeignKey<O, IdsUserSessionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IdsUserSessionsPath(Name alias, Table<IdsUserSessionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IdsUserSessionsPath as(String alias) {
            return new IdsUserSessionsPath(DSL.name(alias), this);
        }

        @Override
        public IdsUserSessionsPath as(Name alias) {
            return new IdsUserSessionsPath(alias, this);
        }

        @Override
        public IdsUserSessionsPath as(Table<?> alias) {
            return new IdsUserSessionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<IdsUserSessionsRecord> getPrimaryKey() {
        return Keys.IDS_USER_SESSIONS__PK___IDS_USER_ID___SESSION_ID;
    }

    @Override
    public List<UniqueKey<IdsUserSessionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.IDS_USER_SESSIONS__UNIQUE___SESSION_ID);
    }

    @Override
    public List<ForeignKey<IdsUserSessionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.IDS_USER_SESSIONS__IDS_USER_SESSIONS__FK___IDS_USER_ID___IDS_USER__ID);
    }

    private transient IdsUserPath _idsUser;

    /**
     * Get the implicit join path to the <code>public.ids_user</code> table.
     */
    public IdsUserPath idsUser() {
        if (_idsUser == null)
            _idsUser = new IdsUserPath(this, Keys.IDS_USER_SESSIONS__IDS_USER_SESSIONS__FK___IDS_USER_ID___IDS_USER__ID, null);

        return _idsUser;
    }

    @Override
    public IdsUserSessions as(String alias) {
        return new IdsUserSessions(DSL.name(alias), this);
    }

    @Override
    public IdsUserSessions as(Name alias) {
        return new IdsUserSessions(alias, this);
    }

    @Override
    public IdsUserSessions as(Table<?> alias) {
        return new IdsUserSessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IdsUserSessions rename(String name) {
        return new IdsUserSessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IdsUserSessions rename(Name name) {
        return new IdsUserSessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IdsUserSessions rename(Table<?> name) {
        return new IdsUserSessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUserSessions where(Condition condition) {
        return new IdsUserSessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUserSessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUserSessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUserSessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IdsUserSessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IdsUserSessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IdsUserSessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IdsUserSessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUserSessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUserSessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
