/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.Keys;
import org.kbalazs.smart_scrum_poker_backend_native.db.Public;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser.IdsUserPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker.PokerPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.InPokerIdsUsersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InPokerIdsUsers extends TableImpl<InPokerIdsUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.in_poker_ids_users</code>
     */
    public static final InPokerIdsUsers IN_POKER_IDS_USERS = new InPokerIdsUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InPokerIdsUsersRecord> getRecordType() {
        return InPokerIdsUsersRecord.class;
    }

    /**
     * The column <code>public.in_poker_ids_users.ids_user_id</code>.
     */
    public final TableField<InPokerIdsUsersRecord, UUID> IDS_USER_ID = createField(DSL.name("ids_user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.in_poker_ids_users.poker_id</code>.
     */
    public final TableField<InPokerIdsUsersRecord, Long> POKER_ID = createField(DSL.name("poker_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.in_poker_ids_users.created_at</code>.
     */
    public final TableField<InPokerIdsUsersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private InPokerIdsUsers(Name alias, Table<InPokerIdsUsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InPokerIdsUsers(Name alias, Table<InPokerIdsUsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.in_poker_ids_users</code> table reference
     */
    public InPokerIdsUsers(String alias) {
        this(DSL.name(alias), IN_POKER_IDS_USERS);
    }

    /**
     * Create an aliased <code>public.in_poker_ids_users</code> table reference
     */
    public InPokerIdsUsers(Name alias) {
        this(alias, IN_POKER_IDS_USERS);
    }

    /**
     * Create a <code>public.in_poker_ids_users</code> table reference
     */
    public InPokerIdsUsers() {
        this(DSL.name("in_poker_ids_users"), null);
    }

    public <O extends Record> InPokerIdsUsers(Table<O> path, ForeignKey<O, InPokerIdsUsersRecord> childPath, InverseForeignKey<O, InPokerIdsUsersRecord> parentPath) {
        super(path, childPath, parentPath, IN_POKER_IDS_USERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InPokerIdsUsersPath extends InPokerIdsUsers implements Path<InPokerIdsUsersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InPokerIdsUsersPath(Table<O> path, ForeignKey<O, InPokerIdsUsersRecord> childPath, InverseForeignKey<O, InPokerIdsUsersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InPokerIdsUsersPath(Name alias, Table<InPokerIdsUsersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InPokerIdsUsersPath as(String alias) {
            return new InPokerIdsUsersPath(DSL.name(alias), this);
        }

        @Override
        public InPokerIdsUsersPath as(Name alias) {
            return new InPokerIdsUsersPath(alias, this);
        }

        @Override
        public InPokerIdsUsersPath as(Table<?> alias) {
            return new InPokerIdsUsersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<InPokerIdsUsersRecord> getPrimaryKey() {
        return Keys.IN_POKER_IDS_USERS__PK___IDS_USER_ID___POKER_ID;
    }

    @Override
    public List<ForeignKey<InPokerIdsUsersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.IN_POKER_IDS_USERS__IN_POKER_IDS_USERS__FK___IDS_USER_ID___IDS_USER__ID___ON_DELETE, Keys.IN_POKER_IDS_USERS__IN_POKER_IDS_USERS__FK___POKER_ID___POKER__ID___ON_DELETE_CASCA);
    }

    private transient IdsUserPath _idsUser;

    /**
     * Get the implicit join path to the <code>public.ids_user</code> table.
     */
    public IdsUserPath idsUser() {
        if (_idsUser == null)
            _idsUser = new IdsUserPath(this, Keys.IN_POKER_IDS_USERS__IN_POKER_IDS_USERS__FK___IDS_USER_ID___IDS_USER__ID___ON_DELETE, null);

        return _idsUser;
    }

    private transient PokerPath _poker;

    /**
     * Get the implicit join path to the <code>public.poker</code> table.
     */
    public PokerPath poker() {
        if (_poker == null)
            _poker = new PokerPath(this, Keys.IN_POKER_IDS_USERS__IN_POKER_IDS_USERS__FK___POKER_ID___POKER__ID___ON_DELETE_CASCA, null);

        return _poker;
    }

    @Override
    public InPokerIdsUsers as(String alias) {
        return new InPokerIdsUsers(DSL.name(alias), this);
    }

    @Override
    public InPokerIdsUsers as(Name alias) {
        return new InPokerIdsUsers(alias, this);
    }

    @Override
    public InPokerIdsUsers as(Table<?> alias) {
        return new InPokerIdsUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InPokerIdsUsers rename(String name) {
        return new InPokerIdsUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InPokerIdsUsers rename(Name name) {
        return new InPokerIdsUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InPokerIdsUsers rename(Table<?> name) {
        return new InPokerIdsUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InPokerIdsUsers where(Condition condition) {
        return new InPokerIdsUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InPokerIdsUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InPokerIdsUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InPokerIdsUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InPokerIdsUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InPokerIdsUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InPokerIdsUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InPokerIdsUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InPokerIdsUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InPokerIdsUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
