/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.Keys;
import org.kbalazs.smart_scrum_poker_backend_native.db.Public;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser.IdsUserPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker.PokerPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote.VotePath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.StoryPointConfigRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoryPointConfig extends TableImpl<StoryPointConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.story_point_config</code>
     */
    public static final StoryPointConfig STORY_POINT_CONFIG = new StoryPointConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoryPointConfigRecord> getRecordType() {
        return StoryPointConfigRecord.class;
    }

    /**
     * The column <code>public.story_point_config.id</code>.
     */
    public final TableField<StoryPointConfigRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.story_point_config.name</code>.
     */
    public final TableField<StoryPointConfigRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.story_point_config.sizes_config</code>.
     */
    public final TableField<StoryPointConfigRecord, JSONB> SIZES_CONFIG = createField(DSL.name("sizes_config"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.story_point_config.dimensions_config</code>.
     */
    public final TableField<StoryPointConfigRecord, JSONB> DIMENSIONS_CONFIG = createField(DSL.name("dimensions_config"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.story_point_config.points_mapping</code>.
     */
    public final TableField<StoryPointConfigRecord, JSONB> POINTS_MAPPING = createField(DSL.name("points_mapping"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.story_point_config.created_at</code>.
     */
    public final TableField<StoryPointConfigRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.story_point_config.created_by</code>.
     */
    public final TableField<StoryPointConfigRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID.nullable(false), this, "");

    private StoryPointConfig(Name alias, Table<StoryPointConfigRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StoryPointConfig(Name alias, Table<StoryPointConfigRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.story_point_config</code> table reference
     */
    public StoryPointConfig(String alias) {
        this(DSL.name(alias), STORY_POINT_CONFIG);
    }

    /**
     * Create an aliased <code>public.story_point_config</code> table reference
     */
    public StoryPointConfig(Name alias) {
        this(alias, STORY_POINT_CONFIG);
    }

    /**
     * Create a <code>public.story_point_config</code> table reference
     */
    public StoryPointConfig() {
        this(DSL.name("story_point_config"), null);
    }

    public <O extends Record> StoryPointConfig(Table<O> path, ForeignKey<O, StoryPointConfigRecord> childPath, InverseForeignKey<O, StoryPointConfigRecord> parentPath) {
        super(path, childPath, parentPath, STORY_POINT_CONFIG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StoryPointConfigPath extends StoryPointConfig implements Path<StoryPointConfigRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StoryPointConfigPath(Table<O> path, ForeignKey<O, StoryPointConfigRecord> childPath, InverseForeignKey<O, StoryPointConfigRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StoryPointConfigPath(Name alias, Table<StoryPointConfigRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StoryPointConfigPath as(String alias) {
            return new StoryPointConfigPath(DSL.name(alias), this);
        }

        @Override
        public StoryPointConfigPath as(Name alias) {
            return new StoryPointConfigPath(alias, this);
        }

        @Override
        public StoryPointConfigPath as(Table<?> alias) {
            return new StoryPointConfigPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<StoryPointConfigRecord, Long> getIdentity() {
        return (Identity<StoryPointConfigRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoryPointConfigRecord> getPrimaryKey() {
        return Keys.STORY_POINT_CONFIG__PK___ID;
    }

    @Override
    public List<ForeignKey<StoryPointConfigRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STORY_POINT_CONFIG__STORY_POINT_CONFIG__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_);
    }

    private transient IdsUserPath _idsUser;

    /**
     * Get the implicit join path to the <code>public.ids_user</code> table.
     */
    public IdsUserPath idsUser() {
        if (_idsUser == null)
            _idsUser = new IdsUserPath(this, Keys.STORY_POINT_CONFIG__STORY_POINT_CONFIG__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_, null);

        return _idsUser;
    }

    private transient PokerPath _poker;

    /**
     * Get the implicit to-many join path to the <code>public.poker</code> table
     */
    public PokerPath poker() {
        if (_poker == null)
            _poker = new PokerPath(this, null, Keys.POKER__POKER__FK___STORY_POINT_CONFIG_ID___STORY_POINT_CONFIG__ID___ON.getInverseKey());

        return _poker;
    }

    private transient VotePath _vote;

    /**
     * Get the implicit to-many join path to the <code>public.vote</code> table
     */
    public VotePath vote() {
        if (_vote == null)
            _vote = new VotePath(this, null, Keys.VOTE__VOTE__FK___STORY_POINT_CONFIG_ID___STORY_POINT_CONFIG__ID___ON_.getInverseKey());

        return _vote;
    }

    @Override
    public StoryPointConfig as(String alias) {
        return new StoryPointConfig(DSL.name(alias), this);
    }

    @Override
    public StoryPointConfig as(Name alias) {
        return new StoryPointConfig(alias, this);
    }

    @Override
    public StoryPointConfig as(Table<?> alias) {
        return new StoryPointConfig(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryPointConfig rename(String name) {
        return new StoryPointConfig(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryPointConfig rename(Name name) {
        return new StoryPointConfig(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoryPointConfig rename(Table<?> name) {
        return new StoryPointConfig(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoryPointConfig where(Condition condition) {
        return new StoryPointConfig(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoryPointConfig where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoryPointConfig where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoryPointConfig where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoryPointConfig where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoryPointConfig where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoryPointConfig where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoryPointConfig where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoryPointConfig whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoryPointConfig whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
