/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.FlywaySchemaHistory;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUserSessions;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InPokerIdsUsers;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Ticket;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.FlywaySchemaHistoryRecord;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.IdsUserRecord;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.IdsUserSessionsRecord;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.InPokerIdsUsersRecord;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.PokerRecord;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.TicketRecord;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.VoteRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<IdsUserRecord> INSECURE_USER__UNIQUE___ID = Internal.createUniqueKey(IdsUser.IDS_USER, DSL.name("insecure_user__unique___id"), new TableField[] { IdsUser.IDS_USER.ID }, true);
    public static final UniqueKey<IdsUserSessionsRecord> IDS_USER_SESSIONS__PK___IDS_USER_ID___SESSION_ID = Internal.createUniqueKey(IdsUserSessions.IDS_USER_SESSIONS, DSL.name("ids_user_sessions__pk___ids_user_id___session_id"), new TableField[] { IdsUserSessions.IDS_USER_SESSIONS.IDS_USER_ID, IdsUserSessions.IDS_USER_SESSIONS.SESSION_ID }, true);
    public static final UniqueKey<IdsUserSessionsRecord> IDS_USER_SESSIONS__UNIQUE___SESSION_ID = Internal.createUniqueKey(IdsUserSessions.IDS_USER_SESSIONS, DSL.name("ids_user_sessions__unique___session_id"), new TableField[] { IdsUserSessions.IDS_USER_SESSIONS.SESSION_ID }, true);
    public static final UniqueKey<InPokerIdsUsersRecord> IN_POKER_IDS_USERS__PK___IDS_USER_ID___POKER_ID = Internal.createUniqueKey(InPokerIdsUsers.IN_POKER_IDS_USERS, DSL.name("in_poker_ids_users__pk___ids_user_id___poker_id"), new TableField[] { InPokerIdsUsers.IN_POKER_IDS_USERS.IDS_USER_ID, InPokerIdsUsers.IN_POKER_IDS_USERS.POKER_ID }, true);
    public static final UniqueKey<PokerRecord> POKER__PK___ID = Internal.createUniqueKey(Poker.POKER, DSL.name("poker__pk___id"), new TableField[] { Poker.POKER.ID }, true);
    public static final UniqueKey<PokerRecord> POKER__UNIQUE___PUBLIC_ID = Internal.createUniqueKey(Poker.POKER, DSL.name("poker__unique___public_id"), new TableField[] { Poker.POKER.PUBLIC_ID }, true);
    public static final UniqueKey<TicketRecord> TICKET__PK___ID = Internal.createUniqueKey(Ticket.TICKET, DSL.name("ticket__pk___id"), new TableField[] { Ticket.TICKET.ID }, true);
    public static final UniqueKey<TicketRecord> TICKET__UNIQUE___PUBLIC_ID = Internal.createUniqueKey(Ticket.TICKET, DSL.name("ticket__unique___public_id"), new TableField[] { Ticket.TICKET.PUBLIC_ID }, true);
    public static final UniqueKey<VoteRecord> VOTE__PK___ID = Internal.createUniqueKey(Vote.VOTE, DSL.name("vote__pk___id"), new TableField[] { Vote.VOTE.ID }, true);
    public static final UniqueKey<VoteRecord> VOTE__UNIQUE___TICKET_ID___CREATED_BY = Internal.createUniqueKey(Vote.VOTE, DSL.name("vote__unique___ticket_id___created_by"), new TableField[] { Vote.VOTE.TICKET_ID, Vote.VOTE.CREATED_BY }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<IdsUserSessionsRecord, IdsUserRecord> IDS_USER_SESSIONS__IDS_USER_SESSIONS__FK___IDS_USER_ID___IDS_USER__ID = Internal.createForeignKey(IdsUserSessions.IDS_USER_SESSIONS, DSL.name("ids_user_sessions__fk___ids_user_id___ids_user__id"), new TableField[] { IdsUserSessions.IDS_USER_SESSIONS.IDS_USER_ID }, Keys.INSECURE_USER__UNIQUE___ID, new TableField[] { IdsUser.IDS_USER.ID }, true);
    public static final ForeignKey<InPokerIdsUsersRecord, IdsUserRecord> IN_POKER_IDS_USERS__IN_POKER_IDS_USERS__FK___IDS_USER_ID___IDS_USER__ID___ON_DELETE = Internal.createForeignKey(InPokerIdsUsers.IN_POKER_IDS_USERS, DSL.name("in_poker_ids_users__fk___ids_user_id___ids_user__id___on_delete"), new TableField[] { InPokerIdsUsers.IN_POKER_IDS_USERS.IDS_USER_ID }, Keys.INSECURE_USER__UNIQUE___ID, new TableField[] { IdsUser.IDS_USER.ID }, true);
    public static final ForeignKey<InPokerIdsUsersRecord, PokerRecord> IN_POKER_IDS_USERS__IN_POKER_IDS_USERS__FK___POKER_ID___POKER__ID___ON_DELETE_CASCA = Internal.createForeignKey(InPokerIdsUsers.IN_POKER_IDS_USERS, DSL.name("in_poker_ids_users__fk___poker_id___poker__id___on_delete_casca"), new TableField[] { InPokerIdsUsers.IN_POKER_IDS_USERS.POKER_ID }, Keys.POKER__PK___ID, new TableField[] { Poker.POKER.ID }, true);
    public static final ForeignKey<PokerRecord, IdsUserRecord> POKER__POKER__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_CASCADE = Internal.createForeignKey(Poker.POKER, DSL.name("poker__fk___created_by___ids_user__id___on_delete_cascade"), new TableField[] { Poker.POKER.CREATED_BY }, Keys.INSECURE_USER__UNIQUE___ID, new TableField[] { IdsUser.IDS_USER.ID }, true);
    public static final ForeignKey<TicketRecord, PokerRecord> TICKET__TICKET__FK___POKER_ID___POKER__ID___ON_DELETE_CASCADE = Internal.createForeignKey(Ticket.TICKET, DSL.name("ticket__fk___poker_id___poker__id___on_delete_cascade"), new TableField[] { Ticket.TICKET.POKER_ID }, Keys.POKER__PK___ID, new TableField[] { Poker.POKER.ID }, true);
    public static final ForeignKey<VoteRecord, IdsUserRecord> VOTE__VOTE__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_CASCADE = Internal.createForeignKey(Vote.VOTE, DSL.name("vote__fk___created_by___ids_user__id___on_delete_cascade"), new TableField[] { Vote.VOTE.CREATED_BY }, Keys.INSECURE_USER__UNIQUE___ID, new TableField[] { IdsUser.IDS_USER.ID }, true);
    public static final ForeignKey<VoteRecord, TicketRecord> VOTE__VOTE__FK___TICKET_ID___TICKET__ID___ON_DELETE_CASCADE = Internal.createForeignKey(Vote.VOTE, DSL.name("vote__fk___ticket_id___ticket__id___on_delete_cascade"), new TableField[] { Vote.VOTE.TICKET_ID }, Keys.TICKET__PK___ID, new TableField[] { Ticket.TICKET.ID }, true);
}
