/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.FlywaySchemaHistory;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUserSessions;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InPokerIdsUsers;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Ticket;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.ids_user</code>.
     */
    public final IdsUser IDS_USER = IdsUser.IDS_USER;

    /**
     * The table <code>public.ids_user_sessions</code>.
     */
    public final IdsUserSessions IDS_USER_SESSIONS = IdsUserSessions.IDS_USER_SESSIONS;

    /**
     * The table <code>public.in_poker_ids_users</code>.
     */
    public final InPokerIdsUsers IN_POKER_IDS_USERS = InPokerIdsUsers.IN_POKER_IDS_USERS;

    /**
     * The table <code>public.poker</code>.
     */
    public final Poker POKER = Poker.POKER;

    /**
     * The table <code>public.ticket</code>.
     */
    public final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>public.vote</code>.
     */
    public final Vote VOTE = Vote.VOTE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            IdsUser.IDS_USER,
            IdsUserSessions.IDS_USER_SESSIONS,
            InPokerIdsUsers.IN_POKER_IDS_USERS,
            Poker.POKER,
            Ticket.TICKET,
            Vote.VOTE
        );
    }
}
