/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db;


import org.kbalazs.smart_scrum_poker_backend_native.db.tables.FlywaySchemaHistory;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUserSessions;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InPokerIdsUsers;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Ticket;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.ids_user</code>.
     */
    public static final IdsUser IDS_USER = IdsUser.IDS_USER;

    /**
     * The table <code>public.ids_user_sessions</code>.
     */
    public static final IdsUserSessions IDS_USER_SESSIONS = IdsUserSessions.IDS_USER_SESSIONS;

    /**
     * The table <code>public.in_poker_ids_users</code>.
     */
    public static final InPokerIdsUsers IN_POKER_IDS_USERS = InPokerIdsUsers.IN_POKER_IDS_USERS;

    /**
     * The table <code>public.poker</code>.
     */
    public static final Poker POKER = Poker.POKER;

    /**
     * The table <code>public.ticket</code>.
     */
    public static final Ticket TICKET = Ticket.TICKET;

    /**
     * The table <code>public.vote</code>.
     */
    public static final Vote VOTE = Vote.VOTE;
}
