/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.Keys;
import org.kbalazs.smart_scrum_poker_backend_native.db.Public;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUserSessions.IdsUserSessionsPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InPokerIdsUsers.InPokerIdsUsersPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker.PokerPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Ticket.TicketPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote.VotePath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.IdsUserRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IdsUser extends TableImpl<IdsUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ids_user</code>
     */
    public static final IdsUser IDS_USER = new IdsUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IdsUserRecord> getRecordType() {
        return IdsUserRecord.class;
    }

    /**
     * The column <code>public.ids_user.id</code>.
     */
    public final TableField<IdsUserRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.ids_user.created_at</code>.
     */
    public final TableField<IdsUserRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private IdsUser(Name alias, Table<IdsUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IdsUser(Name alias, Table<IdsUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ids_user</code> table reference
     */
    public IdsUser(String alias) {
        this(DSL.name(alias), IDS_USER);
    }

    /**
     * Create an aliased <code>public.ids_user</code> table reference
     */
    public IdsUser(Name alias) {
        this(alias, IDS_USER);
    }

    /**
     * Create a <code>public.ids_user</code> table reference
     */
    public IdsUser() {
        this(DSL.name("ids_user"), null);
    }

    public <O extends Record> IdsUser(Table<O> path, ForeignKey<O, IdsUserRecord> childPath, InverseForeignKey<O, IdsUserRecord> parentPath) {
        super(path, childPath, parentPath, IDS_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IdsUserPath extends IdsUser implements Path<IdsUserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IdsUserPath(Table<O> path, ForeignKey<O, IdsUserRecord> childPath, InverseForeignKey<O, IdsUserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IdsUserPath(Name alias, Table<IdsUserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IdsUserPath as(String alias) {
            return new IdsUserPath(DSL.name(alias), this);
        }

        @Override
        public IdsUserPath as(Name alias) {
            return new IdsUserPath(alias, this);
        }

        @Override
        public IdsUserPath as(Table<?> alias) {
            return new IdsUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<UniqueKey<IdsUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.INSECURE_USER__UNIQUE___ID);
    }

    private transient IdsUserSessionsPath _idsUserSessions;

    /**
     * Get the implicit to-many join path to the
     * <code>public.ids_user_sessions</code> table
     */
    public IdsUserSessionsPath idsUserSessions() {
        if (_idsUserSessions == null)
            _idsUserSessions = new IdsUserSessionsPath(this, null, Keys.IDS_USER_SESSIONS__IDS_USER_SESSIONS__FK___IDS_USER_ID___IDS_USER__ID.getInverseKey());

        return _idsUserSessions;
    }

    private transient InPokerIdsUsersPath _inPokerIdsUsers;

    /**
     * Get the implicit to-many join path to the
     * <code>public.in_poker_ids_users</code> table
     */
    public InPokerIdsUsersPath inPokerIdsUsers() {
        if (_inPokerIdsUsers == null)
            _inPokerIdsUsers = new InPokerIdsUsersPath(this, null, Keys.IN_POKER_IDS_USERS__IN_POKER_IDS_USERS__FK___IDS_USER_ID___IDS_USER__ID___ON_DELETE.getInverseKey());

        return _inPokerIdsUsers;
    }

    private transient PokerPath _poker;

    /**
     * Get the implicit to-many join path to the <code>public.poker</code> table
     */
    public PokerPath poker() {
        if (_poker == null)
            _poker = new PokerPath(this, null, Keys.POKER__POKER__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_CASCADE.getInverseKey());

        return _poker;
    }

    private transient VotePath _vote;

    /**
     * Get the implicit to-many join path to the <code>public.vote</code> table
     */
    public VotePath vote() {
        if (_vote == null)
            _vote = new VotePath(this, null, Keys.VOTE__VOTE__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_CASCADE.getInverseKey());

        return _vote;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.ticket</code>
     * table
     */
    public TicketPath ticket() {
        return vote().ticket();
    }

    @Override
    public IdsUser as(String alias) {
        return new IdsUser(DSL.name(alias), this);
    }

    @Override
    public IdsUser as(Name alias) {
        return new IdsUser(alias, this);
    }

    @Override
    public IdsUser as(Table<?> alias) {
        return new IdsUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IdsUser rename(String name) {
        return new IdsUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IdsUser rename(Name name) {
        return new IdsUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IdsUser rename(Table<?> name) {
        return new IdsUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUser where(Condition condition) {
        return new IdsUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IdsUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IdsUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IdsUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IdsUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IdsUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
