/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.Keys;
import org.kbalazs.smart_scrum_poker_backend_native.db.Public;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.InsecureUserSessionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InsecureUserSessions extends TableImpl<InsecureUserSessionsRecord> {

    private static final long serialVersionUID = 1441397877;

    /**
     * The reference instance of <code>public.insecure_user_sessions</code>
     */
    public static final InsecureUserSessions INSECURE_USER_SESSIONS = new InsecureUserSessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InsecureUserSessionsRecord> getRecordType() {
        return InsecureUserSessionsRecord.class;
    }

    /**
     * The column <code>public.insecure_user_sessions.insecure_user_id_secure</code>.
     */
    public final TableField<InsecureUserSessionsRecord, UUID> INSECURE_USER_ID_SECURE = createField(DSL.name("insecure_user_id_secure"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.insecure_user_sessions.session_id</code>.
     */
    public final TableField<InsecureUserSessionsRecord, UUID> SESSION_ID = createField(DSL.name("session_id"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.insecure_user_sessions.created_at</code>.
     */
    public final TableField<InsecureUserSessionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * Create a <code>public.insecure_user_sessions</code> table reference
     */
    public InsecureUserSessions() {
        this(DSL.name("insecure_user_sessions"), null);
    }

    /**
     * Create an aliased <code>public.insecure_user_sessions</code> table reference
     */
    public InsecureUserSessions(String alias) {
        this(DSL.name(alias), INSECURE_USER_SESSIONS);
    }

    /**
     * Create an aliased <code>public.insecure_user_sessions</code> table reference
     */
    public InsecureUserSessions(Name alias) {
        this(alias, INSECURE_USER_SESSIONS);
    }

    private InsecureUserSessions(Name alias, Table<InsecureUserSessionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private InsecureUserSessions(Name alias, Table<InsecureUserSessionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> InsecureUserSessions(Table<O> child, ForeignKey<O, InsecureUserSessionsRecord> key) {
        super(child, key, INSECURE_USER_SESSIONS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<InsecureUserSessionsRecord> getPrimaryKey() {
        return Keys.INSECURE_USER_SESSIONS__PK___INSECURE_USER_ID_SECURE___SESSION_;
    }

    @Override
    public List<UniqueKey<InsecureUserSessionsRecord>> getKeys() {
        return Arrays.<UniqueKey<InsecureUserSessionsRecord>>asList(Keys.INSECURE_USER_SESSIONS__PK___INSECURE_USER_ID_SECURE___SESSION_, Keys.INSECURE_USER_SESSIONS__UNIQUE___SESSION_ID);
    }

    @Override
    public List<ForeignKey<InsecureUserSessionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InsecureUserSessionsRecord, ?>>asList(Keys.INSECURE_USER_SESSIONS__INSECURE_USER_SESSIONS__FK___INSECURE_USER_ID_SECURE___INSECURE);
    }

    public InsecureUser insecureUser() {
        return new InsecureUser(this, Keys.INSECURE_USER_SESSIONS__INSECURE_USER_SESSIONS__FK___INSECURE_USER_ID_SECURE___INSECURE);
    }

    @Override
    public InsecureUserSessions as(String alias) {
        return new InsecureUserSessions(DSL.name(alias), this);
    }

    @Override
    public InsecureUserSessions as(Name alias) {
        return new InsecureUserSessions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InsecureUserSessions rename(String name) {
        return new InsecureUserSessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InsecureUserSessions rename(Name name) {
        return new InsecureUserSessions(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
