/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.Keys;
import org.kbalazs.smart_scrum_poker_backend_native.db.Public;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser.IdsUserPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.InPokerIdsUsers.InPokerIdsUsersPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Ticket.TicketPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.PokerRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Poker extends TableImpl<PokerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.poker</code>
     */
    public static final Poker POKER = new Poker();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PokerRecord> getRecordType() {
        return PokerRecord.class;
    }

    /**
     * The column <code>public.poker.id</code>.
     */
    public final TableField<PokerRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.poker.public_id</code>.
     */
    public final TableField<PokerRecord, UUID> PUBLIC_ID = createField(DSL.name("public_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.poker.name</code>.
     */
    public final TableField<PokerRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.poker.created_at</code>.
     */
    public final TableField<PokerRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.poker.created_by</code>.
     */
    public final TableField<PokerRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID.nullable(false), this, "");

    private Poker(Name alias, Table<PokerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Poker(Name alias, Table<PokerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.poker</code> table reference
     */
    public Poker(String alias) {
        this(DSL.name(alias), POKER);
    }

    /**
     * Create an aliased <code>public.poker</code> table reference
     */
    public Poker(Name alias) {
        this(alias, POKER);
    }

    /**
     * Create a <code>public.poker</code> table reference
     */
    public Poker() {
        this(DSL.name("poker"), null);
    }

    public <O extends Record> Poker(Table<O> path, ForeignKey<O, PokerRecord> childPath, InverseForeignKey<O, PokerRecord> parentPath) {
        super(path, childPath, parentPath, POKER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PokerPath extends Poker implements Path<PokerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PokerPath(Table<O> path, ForeignKey<O, PokerRecord> childPath, InverseForeignKey<O, PokerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PokerPath(Name alias, Table<PokerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PokerPath as(String alias) {
            return new PokerPath(DSL.name(alias), this);
        }

        @Override
        public PokerPath as(Name alias) {
            return new PokerPath(alias, this);
        }

        @Override
        public PokerPath as(Table<?> alias) {
            return new PokerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PokerRecord, Long> getIdentity() {
        return (Identity<PokerRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PokerRecord> getPrimaryKey() {
        return Keys.POKER__PK___ID;
    }

    @Override
    public List<UniqueKey<PokerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.POKER__UNIQUE___PUBLIC_ID);
    }

    @Override
    public List<ForeignKey<PokerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.POKER__POKER__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_CASCADE);
    }

    private transient IdsUserPath _idsUser;

    /**
     * Get the implicit join path to the <code>public.ids_user</code> table.
     */
    public IdsUserPath idsUser() {
        if (_idsUser == null)
            _idsUser = new IdsUserPath(this, Keys.POKER__POKER__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_CASCADE, null);

        return _idsUser;
    }

    private transient InPokerIdsUsersPath _inPokerIdsUsers;

    /**
     * Get the implicit to-many join path to the
     * <code>public.in_poker_ids_users</code> table
     */
    public InPokerIdsUsersPath inPokerIdsUsers() {
        if (_inPokerIdsUsers == null)
            _inPokerIdsUsers = new InPokerIdsUsersPath(this, null, Keys.IN_POKER_IDS_USERS__IN_POKER_IDS_USERS__FK___POKER_ID___POKER__ID___ON_DELETE_CASCA.getInverseKey());

        return _inPokerIdsUsers;
    }

    private transient TicketPath _ticket;

    /**
     * Get the implicit to-many join path to the <code>public.ticket</code>
     * table
     */
    public TicketPath ticket() {
        if (_ticket == null)
            _ticket = new TicketPath(this, null, Keys.TICKET__TICKET__FK___POKER_ID___POKER__ID___ON_DELETE_CASCADE.getInverseKey());

        return _ticket;
    }

    @Override
    public Poker as(String alias) {
        return new Poker(DSL.name(alias), this);
    }

    @Override
    public Poker as(Name alias) {
        return new Poker(alias, this);
    }

    @Override
    public Poker as(Table<?> alias) {
        return new Poker(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Poker rename(String name) {
        return new Poker(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Poker rename(Name name) {
        return new Poker(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Poker rename(Table<?> name) {
        return new Poker(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Poker where(Condition condition) {
        return new Poker(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Poker where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Poker where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Poker where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Poker where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Poker where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Poker where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Poker where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Poker whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Poker whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
