/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.Keys;
import org.kbalazs.smart_scrum_poker_backend_native.db.Public;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser.IdsUserPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Poker.PokerPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Vote.VotePath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.TicketRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ticket extends TableImpl<TicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ticket</code>
     */
    public static final Ticket TICKET = new Ticket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketRecord> getRecordType() {
        return TicketRecord.class;
    }

    /**
     * The column <code>public.ticket.id</code>.
     */
    public final TableField<TicketRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ticket.public_id</code>.
     */
    public final TableField<TicketRecord, UUID> PUBLIC_ID = createField(DSL.name("public_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.ticket.poker_id</code>.
     */
    public final TableField<TicketRecord, Long> POKER_ID = createField(DSL.name("poker_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ticket.name</code>.
     */
    public final TableField<TicketRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.ticket.active</code>.
     */
    public final TableField<TicketRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private Ticket(Name alias, Table<TicketRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Ticket(Name alias, Table<TicketRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ticket</code> table reference
     */
    public Ticket(String alias) {
        this(DSL.name(alias), TICKET);
    }

    /**
     * Create an aliased <code>public.ticket</code> table reference
     */
    public Ticket(Name alias) {
        this(alias, TICKET);
    }

    /**
     * Create a <code>public.ticket</code> table reference
     */
    public Ticket() {
        this(DSL.name("ticket"), null);
    }

    public <O extends Record> Ticket(Table<O> path, ForeignKey<O, TicketRecord> childPath, InverseForeignKey<O, TicketRecord> parentPath) {
        super(path, childPath, parentPath, TICKET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TicketPath extends Ticket implements Path<TicketRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TicketPath(Table<O> path, ForeignKey<O, TicketRecord> childPath, InverseForeignKey<O, TicketRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TicketPath(Name alias, Table<TicketRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TicketPath as(String alias) {
            return new TicketPath(DSL.name(alias), this);
        }

        @Override
        public TicketPath as(Name alias) {
            return new TicketPath(alias, this);
        }

        @Override
        public TicketPath as(Table<?> alias) {
            return new TicketPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TicketRecord> getPrimaryKey() {
        return Keys.TICKET__PK___ID;
    }

    @Override
    public List<UniqueKey<TicketRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TICKET__UNIQUE___PUBLIC_ID);
    }

    @Override
    public List<ForeignKey<TicketRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TICKET__TICKET__FK___POKER_ID___POKER__ID___ON_DELETE_CASCADE);
    }

    private transient PokerPath _poker;

    /**
     * Get the implicit join path to the <code>public.poker</code> table.
     */
    public PokerPath poker() {
        if (_poker == null)
            _poker = new PokerPath(this, Keys.TICKET__TICKET__FK___POKER_ID___POKER__ID___ON_DELETE_CASCADE, null);

        return _poker;
    }

    private transient VotePath _vote;

    /**
     * Get the implicit to-many join path to the <code>public.vote</code> table
     */
    public VotePath vote() {
        if (_vote == null)
            _vote = new VotePath(this, null, Keys.VOTE__VOTE__FK___TICKET_ID___TICKET__ID___ON_DELETE_CASCADE.getInverseKey());

        return _vote;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.ids_user</code> table
     */
    public IdsUserPath idsUser() {
        return vote().idsUser();
    }

    @Override
    public Ticket as(String alias) {
        return new Ticket(DSL.name(alias), this);
    }

    @Override
    public Ticket as(Name alias) {
        return new Ticket(alias, this);
    }

    @Override
    public Ticket as(Table<?> alias) {
        return new Ticket(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ticket rename(String name) {
        return new Ticket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ticket rename(Name name) {
        return new Ticket(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ticket rename(Table<?> name) {
        return new Ticket(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket where(Condition condition) {
        return new Ticket(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ticket where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ticket where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ticket where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ticket where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ticket whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
