/*
 * This file is generated by jOOQ.
 */
package org.kbalazs.smart_scrum_poker_backend_native.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.kbalazs.smart_scrum_poker_backend_native.db.Keys;
import org.kbalazs.smart_scrum_poker_backend_native.db.Public;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.IdsUser.IdsUserPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.Ticket.TicketPath;
import org.kbalazs.smart_scrum_poker_backend_native.db.tables.records.VoteRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Vote extends TableImpl<VoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vote</code>
     */
    public static final Vote VOTE = new Vote();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VoteRecord> getRecordType() {
        return VoteRecord.class;
    }

    /**
     * The column <code>public.vote.id</code>.
     */
    public final TableField<VoteRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vote.ticket_id</code>.
     */
    public final TableField<VoteRecord, Long> TICKET_ID = createField(DSL.name("ticket_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vote.uncertainty</code>.
     */
    public final TableField<VoteRecord, Short> UNCERTAINTY = createField(DSL.name("uncertainty"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.vote.complexity</code>.
     */
    public final TableField<VoteRecord, Short> COMPLEXITY = createField(DSL.name("complexity"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.vote.effort</code>.
     */
    public final TableField<VoteRecord, Short> EFFORT = createField(DSL.name("effort"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.vote.risk</code>.
     */
    public final TableField<VoteRecord, Short> RISK = createField(DSL.name("risk"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.vote.calculated_point</code>.
     */
    public final TableField<VoteRecord, Short> CALCULATED_POINT = createField(DSL.name("calculated_point"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.vote.created_at</code>.
     */
    public final TableField<VoteRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.vote.created_by</code>.
     */
    public final TableField<VoteRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID.nullable(false), this, "");

    private Vote(Name alias, Table<VoteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Vote(Name alias, Table<VoteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vote</code> table reference
     */
    public Vote(String alias) {
        this(DSL.name(alias), VOTE);
    }

    /**
     * Create an aliased <code>public.vote</code> table reference
     */
    public Vote(Name alias) {
        this(alias, VOTE);
    }

    /**
     * Create a <code>public.vote</code> table reference
     */
    public Vote() {
        this(DSL.name("vote"), null);
    }

    public <O extends Record> Vote(Table<O> path, ForeignKey<O, VoteRecord> childPath, InverseForeignKey<O, VoteRecord> parentPath) {
        super(path, childPath, parentPath, VOTE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VotePath extends Vote implements Path<VoteRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VotePath(Table<O> path, ForeignKey<O, VoteRecord> childPath, InverseForeignKey<O, VoteRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VotePath(Name alias, Table<VoteRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VotePath as(String alias) {
            return new VotePath(DSL.name(alias), this);
        }

        @Override
        public VotePath as(Name alias) {
            return new VotePath(alias, this);
        }

        @Override
        public VotePath as(Table<?> alias) {
            return new VotePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<VoteRecord, Long> getIdentity() {
        return (Identity<VoteRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VoteRecord> getPrimaryKey() {
        return Keys.VOTE__PK___ID;
    }

    @Override
    public List<UniqueKey<VoteRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.VOTE__UNIQUE___TICKET_ID___CREATED_BY);
    }

    @Override
    public List<ForeignKey<VoteRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VOTE__VOTE__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_CASCADE, Keys.VOTE__VOTE__FK___TICKET_ID___TICKET__ID___ON_DELETE_CASCADE);
    }

    private transient IdsUserPath _idsUser;

    /**
     * Get the implicit join path to the <code>public.ids_user</code> table.
     */
    public IdsUserPath idsUser() {
        if (_idsUser == null)
            _idsUser = new IdsUserPath(this, Keys.VOTE__VOTE__FK___CREATED_BY___IDS_USER__ID___ON_DELETE_CASCADE, null);

        return _idsUser;
    }

    private transient TicketPath _ticket;

    /**
     * Get the implicit join path to the <code>public.ticket</code> table.
     */
    public TicketPath ticket() {
        if (_ticket == null)
            _ticket = new TicketPath(this, Keys.VOTE__VOTE__FK___TICKET_ID___TICKET__ID___ON_DELETE_CASCADE, null);

        return _ticket;
    }

    @Override
    public Vote as(String alias) {
        return new Vote(DSL.name(alias), this);
    }

    @Override
    public Vote as(Name alias) {
        return new Vote(alias, this);
    }

    @Override
    public Vote as(Table<?> alias) {
        return new Vote(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Vote rename(String name) {
        return new Vote(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vote rename(Name name) {
        return new Vote(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vote rename(Table<?> name) {
        return new Vote(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote where(Condition condition) {
        return new Vote(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vote where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vote where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vote where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vote where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vote whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
