name: "🔎 Dazbo's Gemini Code Review"

on:
  pull_request:
    branches:
      - master
  issue_comment:
    types: [created]

jobs:
  review:
    if: |
      (
        github.event_name == 'issue_comment'
        && github.event.issue.pull_request
        && startsWith(github.event.comment.body, '/gemini-review')
      )
    steps:
      - name: Hello
        run: echo "hello"